Throne.quotes = ["Mr. Freeze, give yourself up. We can get help for you... medical help! - Batman",
"Why is a woman in love like a welder? Because they both carry a torch! - Batman",
"Egads! What sorcery is this? There was enough paralyzing gas in that cork to keep ordinary men unconscious for hours! - Joker",
"You've tripped on one of your tricks this time, Joker! - Robin",
"Here comes the bride, all bagged and tied! - Penguin",
"Holy bill of rights, Batman! - Robin",
"Holy haberdashery, Batman! - Robin",
"Holy atomic pile, Batman! - Robin",
"Holy priceless collection of Etruscan snoods! - Robin",
"Holey rusted metal, Batman! The ground. It's all metal. It's full of holes. You know, holey. - Robin",
"The opposite of a girl is a boy! - Robin",
"It's Alfred's emergency belt-buckle Bat-call signal! He's in trouble! - Batman",
"I never touch spirits. Have you some milk? - Batman",
"Same Bat time, Same bat channel. - Narrator",
"Come on, Robin, to the Bat Cave! There's not a moment to lose! - Batman",
"Wait til they getta loada me - Joker",
"Never rub another man's rhubarb. - Joker",
"I've been dead once already; it's very liberating. You might think of it as... therapy. - Joker",
"You should have let me in on this. We could have planned it, prepared it, pre-sold the movie rights! - Riddler",
"Tell the fat lady she's on in five. - Riddler",
"I hate to disappoint you but my rubber lips are immune to your charms. - Robin",
"So many people to kill... so little time. - Poision Ivy",
"Tonight, hell freezes over! - Mr Freeze",
"It was noble of that animal to hurl himself into the path of that final torpedo. He gave his life for ours - Batman",
"Bless my dustpan! - Alfred",
"Holy demolition, Batman! - Robin",
"Holy heart failure, Batman! - Robin",
"Holy Long John Silver, Batman! - Robin",
"Holy Captain Nemo, Batman! - Robin",
"Holy costume party, Batman! - Robin",
"The batcomputer is none too frisky today, Batman. - Robin",
"It's all a blur. Like a horrible day-mare. - Robin",
"You she-devil! Have you short-circuited Batman's brain? - Robin",
"I bet Batman is the only one in the world with a hand steady enough to paint false fingerprints. - Robin",
"An older head can't be put on younger shoulders. - Batman",
"Stop fiddling with that atomic pile and come down here! - Batman",
"Careful, Robin. Both hands on the Bat-rope. - Batman",
"Remember Robin, always look both ways. - Batman",
"Of course, Robin. Even crime-fighters must eat. And especially you. You're a growing boy and you need your nutrition.",
"Better three hours too soon than a minute too late. - Batman",
"It's sometimes difficult to think clearly when you're strapped to a printing press. - Batman",
"This is torture, at its most bizarre and terrible. - Batman",
"If you can't spend it, money's just a lot of worthless paper, isn't it? - Batman",
"Since there is no life on Mars as we know it, there can be no intelligible Marsish language. - Batman",
"Whatever is fair in love and war is also fair in crimefighting. - Batman",
"Planting a timebomb in a local library is a felony. - Batman"];
